parameters:
  displayName:
  project:
  platformVariableGroup:
  buildConfigurations: [ Debug, Release ]
  msbuildArguments: ''
  debug: false

jobs:
  - job:
    displayName: ${{ parameters.displayName }}

    variables:
    - group: ${{ parameters.platformVariableGroup }}

    pool:
      vmImage: $(Job.VmImage)

    strategy:
      matrix:
        ${{ each configuration in parameters.buildConfigurations }}:
          ${{ configuration }}:
            BuildConfiguration: ${{configuration}}

    steps:
      - bash: |
          cat $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh
          echo 'xcode'
          ls /Library/Frameworks/Mono.framework/Versions/
          ls /Library/Frameworks/Xamarin.Mac.framework/Versions/
          ls -ld /Applications/Xcode*

      - bash: |
          echo 'currmono at /Library/Frameworks/Mono.framework/Versions/Current'
          ls -l /Library/Frameworks/Mono.framework/Versions/Current
          sudo rm -f /Library/Frameworks/Mono.framework/Versions/Current
          sudo ln -s /Library/Frameworks/Mono.framework/Versions/${XAMARINMAC_MONOVERSION} /Library/Frameworks/Mono.framework/Versions/Current
          echo 'newmono at /Library/Frameworks/Mono.framework/Versions/Current'
          ls -l /Library/Frameworks/Mono.framework/Versions/Current

          dotnet --list-sdks

          echo "path:"
          echo $PATH


      # - template: InstallMonoMacOS.yml
      #   parameters:
      #     version: $(XamarinMac.MonoVersion)

      - bash: |
          dotnet --version

      - task: DotNetCoreInstaller@1
        inputs:
          packageType: sdk
          version: $(DotNetCoreSdk.Version)

      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: $(DotNetCoreSdk.Version)

      - bash: |
          dotnet --version

      - task: MSBuild@1
        displayName: Restore Packages
        inputs:
          solution: ${{ parameters.project }}
          #msbuildLocation: /Library/Frameworks/Mono.framework/Versions/$(XamarinMac.MonoVersion)/bin/msbuild
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          msbuildArguments: /t:Restore

      # TODO: Replace with MSBuildSteps
      - task: MSBuild@1
        displayName: Build ${{ parameters.project }}
        inputs:
          solution: ${{ parameters.project }}
          #msbuildLocation: /Library/Frameworks/Mono.framework/Versions/$(XamarinMac.MonoVersion)/bin/msbuild
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          configuration: $(BuildConfiguration)
          platform: AnyCPU
          msbuildArguments:
            ${{ parameters.msbuildArguments }}
#            /p:AutoGenerateBindingRedirects=true
# /p:DepsFileGenerationMode=old
          maximumCpuCount: $(MSBuild.MaximumCpuCount)
