parameters:
  displayName:
  project:
  platformVariableGroup:
  buildConfigurations: [ Debug, Release ]
  msbuildArguments: ''
  debug: false

jobs:
  - job:
    displayName: ${{ parameters.displayName }}

    variables:
    - group: ${{ parameters.platformVariableGroup }}

    pool:
      vmImage: $(Job.VmImage)

    strategy:
      matrix:
        ${{ each configuration in parameters.buildConfigurations }}:
          ${{ configuration }}:
            BuildConfiguration: ${{configuration}}

    steps:
      - bash: |
          ls -l /Library/Frameworks/Mono.framework/Versions/Current
          sudo rm -f /Library/Frameworks/Mono.framework/Versions/Current
          sudo ln -s /Library/Frameworks/Mono.framework/Versions/${XAMARINMAC_MONOVERSION} /Library/Frameworks/Mono.framework/Versions/Current
          ls -l /Library/Frameworks/Mono.framework/Versions/Current

      # - template: InstallMonoMacOS.yml
      #   parameters:
      #     version: $(XamarinMac.MonoVersion)

      - task: DotNetCoreInstaller@1
        inputs:
          packageType: sdk
          version: $(DotNetCoreSdk.Version)

      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: $(DotNetCoreSdk.Version)

      - task: MSBuild@1
        displayName: Restore Packages
        inputs:
          solution: ${{ parameters.project }}
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          msbuildArguments: /t:Restore

      # TODO: Replace with MSBuildSteps
      - task: MSBuild@1
        displayName: Build ${{ parameters.project }}
        inputs:
          solution: ${{ parameters.project }}
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          configuration: $(BuildConfiguration)
          platform: AnyCPU
          msbuildArguments:
            ${{ parameters.msbuildArguments }}
            /p:DepsFileGenerationMode=old
            /p:AutoGenerateBindingRedirects=true
          maximumCpuCount: $(MSBuild.MaximumCpuCount)
