parameters:
  displayName:
  project:
  platformVariableGroup:
  buildConfigurations: [ Debug, Release ]
  msbuildArguments: ''
  debug: false

jobs:
  - job:
    displayName: ${{ parameters.displayName }}

    variables:
    - group: ${{ parameters.platformVariableGroup }}

    pool:
      vmImage: $(Job.VmImage)

    strategy:
      matrix:
        ${{ each configuration in parameters.buildConfigurations }}:
          ${{ configuration }}:
            BuildConfiguration: ${{configuration}}

    steps:
      - bash: |
          # echo "mono*"
          # ls /Library/Frameworks/Mono*/Versions/
          # echo "xam*"
          # ls /Library/Frameworks/Xamarin*/Versions/
          # echo "SH"
          cat $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh
          echo 'xcode'
          # ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
          ls /Library/Frameworks/Mono.framework/Versions/
          ls /Library/Frameworks/Xamarin.Mac.framework/Versions/
          ls -ld /Applications/Xcode*

      - bash: |
          # sudo rm -f /Library/Frameworks/Xamarin.Mac.framework/Versions/Current
          # sudo ln -s /Library/Frameworks/Xamarin.Mac.framework/Versions/${XAMARINMAC_FRAMEWORKVERSION} /Library/Frameworks/Xamarin.Mac.framework/Versions/Current

          echo 'currmono at /Library/Frameworks/Mono.framework/Versions/Current'
          ls -l /Library/Frameworks/Mono.framework/Versions/Current
          sudo rm -f /Library/Frameworks/Mono.framework/Versions/Current
          sudo ln -s /Library/Frameworks/Mono.framework/Versions/${XAMARINMAC_MONOVERSION} /Library/Frameworks/Mono.framework/Versions/Current
          echo 'newmono at /Library/Frameworks/Mono.framework/Versions/Current'
          ls -l /Library/Frameworks/Mono.framework/Versions/Current


      # - template: InstallMonoMacOS.yml
      #   parameters:
      #     version: $(XamarinMac.MonoVersion)

      # - bash: |
      #     echo '/'
      #     ls /Library/Frameworks/Mono.framework/
      #     echo '/ext'
      #     ls /Library/Frameworks/Mono.framework/External/
      #     echo '/ext/xb'
      #     ls /Library/Frameworks/Mono.framework/External/xbuild/
      #     echo '/ext/xb/xam'
      #     ls /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/
      #     echo '/ext/xb/xam/mac'
      #     ls -l /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/

      # - bash: |
      #     $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $XAMARINMAC_MONOVERSION

      # - bash: |
      #     echo '/'
      #     ls /Library/Frameworks/Mono.framework/
      #     echo '/ext'
      #     ls /Library/Frameworks/Mono.framework/External/
      #     echo '/ext/xb'
      #     ls /Library/Frameworks/Mono.framework/External/xbuild/
      #     echo '/ext/xb/xam'
      #     ls /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/
      #     echo '/ext/xb/xam/mac'
      #     ls -l /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/

      - task: DotNetCoreInstaller@1
        inputs:
          packageType: sdk
          version: 2.1.802

      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: 2.1.802

      - task: MSBuild@1
        displayName: Restore Packages
        inputs:
          solution: ${{ parameters.project }}
          #msbuildLocation: /Library/Frameworks/Mono.framework/Versions/$(XamarinMac.MonoVersion)/bin/msbuild
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          msbuildArguments: /t:Restore

      # TODO: Replace with MSBuildSteps
      - task: MSBuild@1
        displayName: Build ${{ parameters.project }}
        inputs:
          solution: ${{ parameters.project }}
          #msbuildLocation: /Library/Frameworks/Mono.framework/Versions/$(XamarinMac.MonoVersion)/bin/msbuild
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          configuration: $(BuildConfiguration)
          platform: AnyCPU
          msbuildArguments:
            ${{ parameters.msbuildArguments }}
# /p:DepsFileGenerationMode=old
          maximumCpuCount: $(MSBuild.MaximumCpuCount)
