parameters:
  # name:
  displayName:
  project:
  platformVariableGroups: []
  platformVariableGroup: '' # Until we can pass the group array above
  buildPlatforms: []
  buildConfigurations: [ Debug, Release ]
  msbuildArguments: ''
  debug: false

jobs:
  - job: #${{ parameters.name }}
    displayName: ${{ parameters.displayName }}

    variables:
      #${{each group in parameters.platformVariableGroups}}:
      - group: ${{ parameters.platformVariableGroup }}

    pool:
      vmImage: $(Job.VmImage)

    strategy:
      matrix:
        ${{ each configuration in parameters.buildConfigurations }}:
          ${{ each platform in parameters.buildPlatforms }}:
            "${{ platform }}|${{ configuration }}":
              BuildPlatform: ${{platform}}
              BuildConfiguration: ${{configuration}}

    steps:
      - checkout: self
        clean: false

      - template: MSBuildSteps.yml
        parameters:
          project: ${{ parameters.project }}
          msbuildArguments: ${{ parameters.msbuildArguments }}
          debug: ${{ parameters.debug }}
