# Expected variables:
#   - XamarinAndroid.MonoVersion

parameters:
  # name:
  displayName:
  project:
  platformVariableGroup: ''
  buildConfigurations: [ Debug, Release ]

  # XamarinAndroid
  createAppPackage: false
  buildForSimulator: true
  msbuildArguments: ''

  debug: false

jobs:
  - job:
    displayName: ${{ parameters.displayName }}

    variables:
      - group: ${{ parameters.platformVariableGroup }}

    pool:
      vmImage: $(Job.VmImage)

    strategy:
      matrix:
        ${{ each configuration in parameters.buildConfigurations }}:
            "${{ configuration }}":
              BuildConfiguration: ${{ configuration }}

    steps:
      - checkout: self
        clean: false

      - task: DotNetCoreInstaller@1
        inputs:
          version: 3.x

      - powershell: |
          ls /Library/Frameworks/Mono.framework/Versions
          /Library/Frameworks/Mono.framework/Versions/6.0.0/bin/mono /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/15.0/bin/Roslyn/csc.exe /langversion:?
        #condition: ${{ parameters.debug }}

      - task: MSBuild@1
        displayName: Restore Packages
        inputs:
          solution: ${{ parameters.project }}
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          msbuildLocation: /Library/Frameworks/Mono.framework/Versions/$(XamarinAndroid.MonoVersion)/bin/msbuild
          msbuildArguments: /t:Restore

      - task: XamarinAndroid@1
        displayName: Build ${{ parameters.project }}
        inputs:
          projectFile: ${{ parameters.project }}
          configuration: $(BuildConfiguration)
          createAppPackage: ${{ parameters.createAppPackage }}
          clean: false
          msbuildFile: /Library/Frameworks/Mono.framework/Versions/$(XamarinAndroid.MonoVersion)/bin/msbuild

