# Expected variables:
#   - XamariniOS.MonoVersion

parameters:
  # name:
  displayName:
  project:
  platformVariableGroup: ''
  buildConfigurations: [ Debug, Release ]

  # XamariniOS
  packageApp: false
  buildForSimulator: true
  xcodeArguments: ''
  signingIdentity: ''
  signingProvisioningProfileID: ''

  debug: false

jobs:
  - job: #${{ parameters.name }}
    displayName: ${{ parameters.displayName }}

    variables:
      - group: ${{ parameters.platformVariableGroup }}

    pool:
      vmImage: $(Job.VmImage)

    strategy:
      matrix:
        ${{ each configuration in parameters.buildConfigurations }}:
            "${{ configuration }}":
              BuildConfiguration: ${{ configuration }}

    steps:
      - checkout: self
        clean: false

      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            ls /Library/Frameworks/Mono.framework/Versions/
        condition: ${{ parameters.debug }}

      - task: DotNetCoreInstaller@1
        inputs:
          version: 3.x

      - bash: |
          curl -O https://download.mono-project.com/archive/${XAMARINANDROID_MONOVERSION}/macos-10-universal/MonoFramework-MDK-${XAMARINANDROID_MONOVERSION}.macos10.xamarin.universal.pkg
          sudo installer MonoFramework-MDK-${XAMARINANDROID_MONOVERSION}.macos10.xamarin.universal.pkg -target /

      - task: MSBuild@1
        displayName: Restore Packages
        inputs:
          solution: ${{ parameters.project }}
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          msbuildLocation: /Library/Frameworks/Mono.framework/Versions/$(XamariniOS.MonoVersion)/bin/msbuild
          msbuildArguments: /t:Restore

      - task: XamariniOS@2
        displayName: Build ${{ parameters.project }}
        inputs:
          solutionFile: ${{ parameters.project }}
          configuration: $(BuildConfiguration)
          clean: true
          packageApp: ${{ parameters.packageApp }}
          buildForSimulator: ${{ parameters.buildForSimulator }}
          args: ${{ parameters.xcodeArguments }}
          mdtoolFile: /Library/Frameworks/Mono.framework/Versions/$(XamariniOS.MonoVersion)/bin/msbuild
          signingIdentity: ${{ parameters.signingIdentity }}
          signingProvisioningProfileID: ${{ parameters.signingProvisioningProfileID }}
