# Expected variables:
#   - DotNetCoreSdk.Version
#   - XamarinAndroid.MonoVersion

parameters:
  # name:
  displayName:
  project:
  platformVariableGroup: ''
  buildConfigurations: [ Debug, Release ]

  # XamarinAndroid
  createAppPackage: false
  buildForSimulator: true
  msbuildArguments: ''

  debug: false

jobs:
  - job:
    displayName: ${{ parameters.displayName }}

    variables:
      - group: ${{ parameters.platformVariableGroup }}

    pool:
      vmImage: $(Job.VmImage)

    strategy:
      matrix:
        ${{ each configuration in parameters.buildConfigurations }}:
            "${{ configuration }}":
              BuildConfiguration: ${{ configuration }}

    steps:
      - checkout: self
        clean: false

      # - template: InstallMonoMacOS.yml
      #   parameters:
      #     version: $(XamarinAndroid.MonoVersion)

      - bash: |
          ls -l /Library/Frameworks/Mono.framework/Versions/Current
          sudo rm -f /Library/Frameworks/Mono.framework/Versions/Current
          sudo ln -s /Library/Frameworks/Mono.framework/Versions/${XAMARINANDROID_MONOVERSION} /Library/Frameworks/Mono.framework/Versions/Current
          ls -l /Library/Frameworks/Mono.framework/Versions/Current

      - bash: |
          ls -l /Library/Frameworks/Xamarin.Android.framework/Versions/

      - task: DotNetCoreInstaller@1
        inputs:
          packageType: sdk
          version: $(DotNetCoreSdk.Version)

      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: $(DotNetCoreSdk.Version)

      - task: MSBuild@1
        displayName: Restore Packages
        inputs:
          solution: ${{ parameters.project }}
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          msbuildArguments: /t:Restore

      - task: XamarinAndroid@1
        displayName: Build ${{ parameters.project }}
        inputs:
          projectFile: ${{ parameters.project }}
          configuration: $(BuildConfiguration)
          createAppPackage: ${{ parameters.createAppPackage }}
          clean: false
