name: $(BuildId)

trigger:
  branches:
    include:
      - azure/pipes/init

variables:
  - group: Global Build Variables

jobs:

  - job:
    displayName: Windows Forms

    variables:
      - group: Windows Build Variables

    pool:
      vmImage: $(VmImage)

    strategy:
      matrix:
        'Any CPU|Debug':
          BuildPlatform: AnyCPU
          BuildConfiguration: Debug
        'Any CPU|Release':
          BuildPlatform: AnyCPU
          BuildConfiguration: Release

  - job:
    displayName: Windows Universal

    variables:
      - group: Windows Build Variables

    pool:
      vmImage: $(VmImage)

    strategy:
      matrix:
        'x64|Debug':
          BuildPlatform: x64
          BuildConfiguration: Debug
        'x86|Debug':
          BuildPlatform: x86
          BuildConfiguration: Debug
        # 'ARM|Debug':
        #   BuildPlatform: ARM
        #   BuildConfiguration: Debug
        'x64|Release':
          BuildPlatform: x64
          BuildConfiguration: Release
        'x86|Release':
          BuildPlatform: x86
          BuildConfiguration: Release
        # 'ARM|Release':
        #   BuildPlatform: ARM
        #   BuildConfiguration: Release

    steps:
      - checkout: self
        clean: false

      - task: MSBuild@1
        displayName: Restore Packages
        inputs:
          solution: $(Build.SourcesDirectory)/UWP/Unjammit.UWP.csproj
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          maximumCpuCount: $(MSBuild.MaximumCpuCount)
          msbuildArguments: /t:Restore

      - task: MSBuild@1
        displayName: Build Solution
        inputs:
          solution: $(Build.SourcesDirectory)/UWP/Unjammit.UWP.csproj
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
          # msbuildArguments: /p:AppxBundle=Always /p:AppxBundlePlatforms="$(BuildPlatform)" /p:UapAppxPackageBuildMode=StoreUpload /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\AppPackages\\"
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          maximumCpuCount: $(MSBuild.MaximumCpuCount)
          msbuildArguments: /p:AppxBundle=Always /p:AppxBundlePlatforms="$(BuildPlatform)" /p:UapAppxPackageBuildMode=StoreUpload /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\AppPackages\\"

  # - template: Templates/MSBuild.yml
  #   parameters:
  #     name: UWP
  #     displayName: Windows Universal
  #     projects: $(Build.SourcesDirectory)/UWP/Unjammit.UWP.csproj
  #     platformVariableGroup: Windows Build Variables
  #     buildPlatforms: [ x64, x86 ]
  #     msbuildArguments: '/p:AppxBundle=Always /p:AppxBundlePlatforms="$(BuildPlatform)" /p:UapAppxPackageBuildMode=StoreUpload /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\AppPackages\\"'
  #     showVars: true

  # - template: Templates/MSBuild.yml
  #   parameters:
  #     name: WinForms
  #     displayName: Windows Forms
  #     projects: $(Build.SourcesDirectory)/WinForms/Jam.NET.csproj
  #     platformVariableGroup: Windows Build Variables
  #     buildPlatforms: [ 'Any CPU' ]

  # - template: Templates/XamariniOS.yml
  #   parameters:
  #     name: iOS
  #     displayName: iOS
  #     project: $(Build.SourcesDirectory)/iOS/Unjammit.iOS.csproj
  #     platformVariableGroup: iOS Build Variables

