name: Pull Request

trigger: none

jobs:
  - job:
    displayName: Windows Universal

    variables:
      - group: Windows Build Variables
      - group: Global Build Variables

    #strategy:
    pool:
      - name: windows-2019
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 5

    steps:
      - checkout: self
        clean: false

      - task: PowerShell@2
        displayName: Show Variables
        inputs:
          targetType: inline
          script: |
            echo "[" + $env:Job_VmImage
            echo "[" + $env:TimeoutInMinutes
            echo "[" + $env:CancelTimeoutInMinutes
      - task: MSBuild@1
        displayName: Restore Packages
        inputs:
          solution: $(Build.SourcesDirectory)/UWP/Unjammit.UWP.csproj
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          msbuildArguments: /t:Restore

      - task: MSBuild@1
        displayName: Build Unjammit.UWP
        inputs:
          solution: $(Build.SourcesDirectory)/UWP/Unjammit.UWP.csproj
          msbuildArchitecture: $(MSBuild.MSBuildArchitecture)
          configuration: $(BuildConfiguration)
          platform: $(BuildPlatform)
          msbuildArguments: |
            /p:AppxBundle=Always
            /p:AppxBundlePlatforms="$(BuildPlatform)"
            /p:UapAppxPackageBuildMode=StoreUpload
            /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\AppPackages\\"
          clean: true
          maximumCpuCount: $(MSBuild.MaximumCpuCount)
