name: $(BuildId)

trigger: none

jobs:

  - template: Templates/MSBuild.yml
    parameters:
      name: UWP
      displayName: Windows Universal
      projects: $(Build.SourcesDirectory)/UWP/Unjammit.UWP.csproj
      platformVariableGroup: Windows Build Variables
      buildPlatforms: [ x64, x86 ]
      msbuildArguments: '/p:AppxBundle=Always /p:AppxBundlePlatforms="$(BuildPlatform)" /p:UapAppxPackageBuildMode=StoreUpload /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\AppPackages\\"'
      showVars: true

  - template: Templates/MSBuild.yml
    parameters:
      name: WinForms
      displayName: Jam.NET
      projects: $(Build.SourcesDirectory)/WinForms/Jam.NET.csproj
      platformVariableGroup: Windows Build Variables
      buildPlatforms: [ 'Any CPU' ]

  - template: Templates/XamariniOS.yml
    parameters:
      name: iOS
      displayName: iOS
      project: $(Build.SourcesDirectory)/iOS/Unjammit.iOS.csproj
      platformVariableGroup: iOS Build Variables

